name: Tests (conda)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install conda (Mambaforge)
      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: dmf
          python-version: "3.10"
          environment-file: ""
          channels: conda-forge
          use-mamba: true

      - name: Install conda dependencies
        run: |
          mamba install -c conda-forge ase cyipopt numpy pytest

      - name: Install DMF
        run: |
          pip install -e .

      - name: Run tests
        run: pytest -v

